[package]
name = "memcached-rs"
version = "0.0.2"
authors = ["Y. T. CHUNG <zonyitoo@gmail.com>"]
description = "A MemCached Library in Rust"
repository = "https://github.com/zonyitoo/memcached-rs"
keywords = ["memcached"]
license = "MIT"

[lib]
name = "memcached"

[dependencies]
byteorder = "*"
semver = "*"
rand = "*"
#crc32 = "*"

[dependencies.crc32]
git = "https://github.com/zonyitoo/crc32.git"
